language: node_js
node_js: lts/*
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
addons:
  code_climate:
    repo_token:
      secure: "lsTGLtYlStEZXJprJ+pPinF3IQJKDDaeglHa91sgD+xCYjYBW8lfyoxJTPsjikKOrIpGGncZxF6FpB9bouowR+F0F0ZvG1PKaFcQl3C35L+qmYWTG6aC77FMp52QbT7c4iGItuDPWET7sddXWSyVvvQ7Und8uhrnS+dunQnB4U4MPl3GxTH3a0RP6ufHxw8vf2N+NYDYOQnisfSNAtYg1a9YR5sqzVpK6xyzSgf3yoSaArhmxGYNVSCrf06xd/5HAiUx0bANahd3nW6luTqt4+OlIv+jyDnKfmoljIJA+bryMSyQ37S8BVXHXpAFD/SVC4sEztorelwd+MEftveekMsY4v3GCiXHFS3YUCD1R4FJ/5BqmXSdVApLkXoMJI8uBFZ1xV3AGzM3Y/Vjso6h7AOPL/+AFVsvHjPfuVpLzoVlDRQX9lFyLxwZYPop5W6W1qVQDRPyVma7/rtjNhUTT9nPL0mQInsPjndwy+httexRt1BY4bLuXGSs90weCOg7fkMWYM/wyeZEGMHxL9eTMbVK/7yxkjTwAo5SSPjHqMPvlG1WFw6FlpGRrTYQ04HqUrXHixWRSK5sLQI/s8cAmN4TR3lVrvGTGrsRYwGaGclFLPwSN3zAxNkD9rNbfc8xzrB/V5QQkNDrgDUTpKQCA2EmY/88eENokI3akGblK7w="
after_script:
  - codeclimate-test-reporter < coverage/**/lcov.info
notifications:
  slack:
    secure: "qtdEEislS28GQnAADGtYGa40/7beYhvja35w6a/P4VX/Xk4uTGPIUZgU+8uSaDyq30Y8zglZqzUk3trG04tm+azWz7bC0gKYqp37njnc6c2OuglGEzTsazoQMGXCJSosI0mINhr8j9HqyAs2wWG4W74T5QrXIjL2veehetSuMafoe4eErzBhHgPN+tGVcq0t7b+IbZDoGEza4AdgNGbwXCqFRwRQobKd4atT/omsLvr6biH2NDPICSGnfsVWRndaO0eb/urejCFdNgF3Bwn5MSjqqEqezC92CXabDoUdaIqRszd1xkkS7rlr6KU/wBRd1JR8xVkp3/NnSQ8d64227NxDGmq+0Tv9Y1wqG5pJPeTkQ7UNijagJFphNJWeSV23/3drVVsnZvbinNXRaCKyXJmLhKjxL3Mp7i/sDAF9JijR3+sJa6h4dJyzCixwSq4L4tZAMiRSMjWfdnGck+RvkfQWsRbqjAAiQSCGfKxMFsDtVeAgtHKUyP4DGPNJjqHwVzN64glOFymtts+psK7DLHhsRb6ofbGiVjcnVYwM03/crKm4eu8uRods4Y6Zbw3LYvxLKf4SZJzc0EuO6wgtgzSkf99p10e10geG8MUHsHAHWygAW2CdbrgfA53wlIQe5u/w9H+1ypHUqjBS7OF4I2tnBIeNcPlkj+nU1C1uIYk="
    on_success: change